# SPDX-License-Identifier: Apache-2.0
"""Modèle de domaine : messages, blocs, usage, outils, flux des modèles, état d'un run."""

from loom_ia.core.model.base import DomainModel
from loom_ia.core.model.content import (
    AnthropicMeta,
    ArtifactRefBlock,
    ContentBlock,
    JsonBlock,
    OpenAIMeta,
    OutputBlock,
    ProviderMeta,
    ReasoningBlock,
    TextBlock,
    ToolCallBlock,
    ToolOutput,
    ToolResultBlock,
)
from loom_ia.core.model.context import CallerContext
from loom_ia.core.model.ids import (
    DEFAULT_TENANT,
    EventId,
    RunId,
    SessionId,
    SpanId,
    TenantId,
    new_event_id,
    new_id,
    new_run_id,
    new_span_id,
)
from loom_ia.core.model.messages import Message, Role
from loom_ia.core.model.model_spec import (
    ModelApi,
    ModelCapabilities,
    ModelSpec,
    ModelTimeouts,
    RetryPolicy,
    Sdk,
)
from loom_ia.core.model.run_state import PendingCall, RunState, RunStatus
from loom_ia.core.model.streaming import (
    INVALID_JSON_KEY,
    ModelChunk,
    ModelErrorKind,
    ModelRequest,
    ModelResponse,
    ReasoningDelta,
    ResponseAccumulator,
    Stopped,
    StopReason,
    StreamReset,
    TextDelta,
    ToolArgsDelta,
    ToolCallEnded,
    ToolCallStarted,
    ToolChoice,
    UsageDelta,
    message_to_chunks,
)
from loom_ia.core.model.tooling import (
    TOOL_NAME_PATTERN,
    Approval,
    SideEffects,
    ToolDefinition,
    ToolKind,
    ToolSpec,
)
from loom_ia.core.model.usage import Pricing, Usage

__all__ = [
    "DEFAULT_TENANT",
    "INVALID_JSON_KEY",
    "TOOL_NAME_PATTERN",
    "AnthropicMeta",
    "Approval",
    "ArtifactRefBlock",
    "CallerContext",
    "ContentBlock",
    "DomainModel",
    "EventId",
    "JsonBlock",
    "Message",
    "ModelApi",
    "ModelCapabilities",
    "ModelChunk",
    "ModelErrorKind",
    "ModelRequest",
    "ModelResponse",
    "ModelSpec",
    "ModelTimeouts",
    "OpenAIMeta",
    "OutputBlock",
    "PendingCall",
    "Pricing",
    "ProviderMeta",
    "ReasoningBlock",
    "ReasoningDelta",
    "ResponseAccumulator",
    "RetryPolicy",
    "Role",
    "RunId",
    "RunState",
    "RunStatus",
    "Sdk",
    "SessionId",
    "SideEffects",
    "SpanId",
    "StopReason",
    "Stopped",
    "StreamReset",
    "TenantId",
    "TextBlock",
    "TextDelta",
    "ToolArgsDelta",
    "ToolCallBlock",
    "ToolCallEnded",
    "ToolCallStarted",
    "ToolChoice",
    "ToolDefinition",
    "ToolKind",
    "ToolOutput",
    "ToolResultBlock",
    "ToolSpec",
    "Usage",
    "UsageDelta",
    "message_to_chunks",
    "new_event_id",
    "new_id",
    "new_run_id",
    "new_span_id",
]
